
"""ONECTA Cloud API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

from __future__ import annotations

import json
import pprint
import re  # noqa: F401
from typing import Any
from typing import ClassVar
from typing import Self

from pydantic import BaseModel
from pydantic import ConfigDict
from pydantic import Field
from pydantic import StrictStr

from openapi_client.models.boolean_characteristic import BooleanCharacteristic
from openapi_client.models.management_point import ManagementPoint


class GatewayDevice(BaseModel):
    """GatewayDevice
    """

    is_cloud_connection_up: BooleanCharacteristic | None = Field(
        default=None, alias='isCloudConnectionUp'
    )
    timestamp: StrictStr | None = Field(
        default=None,
        description='dateTime when gateway device was last updated',
    )
    mananagement_points: list[ManagementPoint] | None = Field(
        default=None, alias='mananagementPoints'
    )
    id: StrictStr | None = Field(default=None, description='Object Id')
    embedded_id: StrictStr | None = Field(
        default=None, description='The internal device id', alias='embeddedId'
    )
    device_model: StrictStr | None = Field(
        default=None,
        description='The model of the gateway device',
        alias='deviceModel',
    )
    __properties: ClassVar[list[str]] = ['id', 'embeddedId', 'deviceModel']

    model_config = ConfigDict(
        populate_by_name=True, validate_assignment=True, protected_namespaces=()
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self | None:
        """Create an instance of GatewayDevice from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: set[str] = set([])

        _dict = self.model_dump(
            by_alias=True, exclude=excluded_fields, exclude_none=True
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: dict[str, Any] | None) -> Self | None:
        """Create an instance of GatewayDevice from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                'id': obj.get('id'),
                'embeddedId': obj.get('embeddedId'),
                'deviceModel': obj.get('deviceModel'),
            }
        )
        return _obj
