
"""ONECTA Cloud API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

from __future__ import annotations

import json
import pprint
import re  # noqa: F401
from typing import Any
from typing import ClassVar
from typing import Self

from pydantic import BaseModel
from pydantic import ConfigDict
from pydantic import Field
from pydantic import StrictBool
from pydantic import StrictStr
from pydantic import field_validator


class ObjectCharacteristicMetaData(BaseModel):
    """ObjectCharacteristicMetaData
    """

    error: StrictStr | None = None
    settable: StrictBool | None = Field(
        default=None,
        description='Whether or not the characteristic can be changed by the user',
    )
    deprecated: StrictStr | None = Field(
        default=None,
        description='Whether or not the characteristic is deprecated',
    )
    value: dict[str, Any] | None = Field(
        default=None,
        description='The detail of this object can be found in the JSON schemas',
    )
    __properties: ClassVar[list[str]] = [
        'error',
        'settable',
        'deprecated',
        'value',
    ]

    @field_validator('error')
    def error_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['INVALID_CHARACTERISTIC']):
            raise ValueError(
                "must be one of enum values ('INVALID_CHARACTERISTIC')"
            )
        return value

    model_config = ConfigDict(
        populate_by_name=True, validate_assignment=True, protected_namespaces=()
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self | None:
        """Create an instance of ObjectCharacteristicMetaData from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: set[str] = set([])

        _dict = self.model_dump(
            by_alias=True, exclude=excluded_fields, exclude_none=True
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: dict[str, Any] | None) -> Self | None:
        """Create an instance of ObjectCharacteristicMetaData from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                'error': obj.get('error'),
                'settable': obj.get('settable'),
                'deprecated': obj.get('deprecated'),
                'value': obj.get('value'),
            }
        )
        return _obj
