
"""ONECTA Cloud API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 1.0.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

from __future__ import annotations

import json
import pprint
import re  # noqa: F401
from typing import Any
from typing import ClassVar
from typing import Self

from pydantic import BaseModel
from pydantic import ConfigDict
from pydantic import Field
from pydantic import StrictStr
from pydantic import field_validator

from openapi_client.models.site_body_location import SiteBodyLocation
from openapi_client.models.site_body_users_inner import SiteBodyUsersInner


class SitesInner(BaseModel):
    """SitesInner
    """

    gateway_devices: list[StrictStr] | None = Field(
        default=None, alias='gatewayDevices'
    )
    id: StrictStr | None = Field(default=None, description='Object Id')
    name: StrictStr | None = Field(
        default=None, description='The name of the site'
    )
    role: StrictStr | None = Field(
        default=None, description='The role of the user who did the request'
    )
    location: SiteBodyLocation | None = None
    users: list[SiteBodyUsersInner] | None = Field(
        default=None, description='The users that are linked to a site'
    )
    __properties: ClassVar[list[str]] = [
        'id',
        'name',
        'role',
        'location',
        'users',
    ]

    @field_validator('role')
    def role_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['user', 'admin']):
            raise ValueError("must be one of enum values ('user', 'admin')")
        return value

    model_config = ConfigDict(
        populate_by_name=True, validate_assignment=True, protected_namespaces=()
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self | None:
        """Create an instance of SitesInner from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: set[str] = set([])

        _dict = self.model_dump(
            by_alias=True, exclude=excluded_fields, exclude_none=True
        )
        # override the default output from pydantic by calling `to_dict()` of location
        if self.location:
            _dict['location'] = self.location.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in users (list)
        _items = []
        if self.users:
            for _item_users in self.users:
                if _item_users:
                    _items.append(_item_users.to_dict())
            _dict['users'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: dict[str, Any] | None) -> Self | None:
        """Create an instance of SitesInner from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                'id': obj.get('id'),
                'name': obj.get('name'),
                'role': obj.get('role'),
                'location': SiteBodyLocation.from_dict(obj['location'])
                if obj.get('location') is not None
                else None,
                'users': [
                    SiteBodyUsersInner.from_dict(_item)
                    for _item in obj['users']
                ]
                if obj.get('users') is not None
                else None,
            }
        )
        return _obj
