# coding: utf-8

"""
    ONECTA Cloud API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.string_characteristic_meta_data import StringCharacteristicMetaData

class TestStringCharacteristicMetaData(unittest.TestCase):
    """StringCharacteristicMetaData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> StringCharacteristicMetaData:
        """Test StringCharacteristicMetaData
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `StringCharacteristicMetaData`
        """
        model = StringCharacteristicMetaData()
        if include_optional:
            return StringCharacteristicMetaData(
                error = 'INVALID_CHARACTERISTIC',
                settable = True,
                deprecated = '',
                value = '',
                max_length = 1.337
            )
        else:
            return StringCharacteristicMetaData(
        )
        """

    def testStringCharacteristicMetaData(self):
        """Test StringCharacteristicMetaData"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
