# coding: utf-8

"""
    ONECTA Cloud API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.characteristic_api import CharacteristicApi


class TestCharacteristicApi(unittest.TestCase):
    """CharacteristicApi unit test stubs"""

    def setUp(self) -> None:
        self.api = CharacteristicApi()

    def tearDown(self) -> None:
        pass

    def test_gateway_devices_gateway_device_id_management_points_embedded_id_characteristics_name_patch(self) -> None:
        """Test case for gateway_devices_gateway_device_id_management_points_embedded_id_characteristics_name_patch

        Update characteristic information.
        """
        pass


if __name__ == '__main__':
    unittest.main()
