# coding: utf-8

"""
    ONECTA Cloud API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.info_api import InfoApi


class TestInfoApi(unittest.TestCase):
    """InfoApi unit test stubs"""

    def setUp(self) -> None:
        self.api = InfoApi()

    def tearDown(self) -> None:
        pass

    def test_info_get(self) -> None:
        """Test case for info_get

        Get service information
        """
        pass


if __name__ == '__main__':
    unittest.main()
