# coding: utf-8

"""
    ONECTA Cloud API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.schedule_api import ScheduleApi


class TestScheduleApi(unittest.TestCase):
    """ScheduleApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ScheduleApi()

    def tearDown(self) -> None:
        pass

    def test_gateway_devices_gateway_device_id_management_points_embedded_id_schedule_mode_current_put(self) -> None:
        """Test case for gateway_devices_gateway_device_id_management_points_embedded_id_schedule_mode_current_put

        Update the current schedule
        """
        pass


if __name__ == '__main__':
    unittest.main()
