# coding: utf-8

"""
    ONECTA Cloud API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.site_api import SiteApi


class TestSiteApi(unittest.TestCase):
    """SiteApi unit test stubs"""

    def setUp(self) -> None:
        self.api = SiteApi()

    def tearDown(self) -> None:
        pass

    def test_sites_get(self) -> None:
        """Test case for sites_get

        Get all the sites related to the user.
        """
        pass


if __name__ == '__main__':
    unittest.main()
