# coding: utf-8

"""
    ONECTA Cloud API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.current_schedule import CurrentSchedule

class TestCurrentSchedule(unittest.TestCase):
    """CurrentSchedule unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CurrentSchedule:
        """Test CurrentSchedule
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CurrentSchedule`
        """
        model = CurrentSchedule()
        if include_optional:
            return CurrentSchedule(
                schedule_id = '',
                enabled = True
            )
        else:
            return CurrentSchedule(
                schedule_id = '',
                enabled = True,
        )
        """

    def testCurrentSchedule(self):
        """Test CurrentSchedule"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
