# coding: utf-8

"""
    ONECTA Cloud API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.gateway_devices_gateway_device_id_get404_response import GatewayDevicesGatewayDeviceIdGet404Response

class TestGatewayDevicesGatewayDeviceIdGet404Response(unittest.TestCase):
    """GatewayDevicesGatewayDeviceIdGet404Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GatewayDevicesGatewayDeviceIdGet404Response:
        """Test GatewayDevicesGatewayDeviceIdGet404Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GatewayDevicesGatewayDeviceIdGet404Response`
        """
        model = GatewayDevicesGatewayDeviceIdGet404Response()
        if include_optional:
            return GatewayDevicesGatewayDeviceIdGet404Response(
                code = 'GATEWAY_DEVICE_MISSING',
                message = ''
            )
        else:
            return GatewayDevicesGatewayDeviceIdGet404Response(
                code = 'GATEWAY_DEVICE_MISSING',
                message = '',
        )
        """

    def testGatewayDevicesGatewayDeviceIdGet404Response(self):
        """Test GatewayDevicesGatewayDeviceIdGet404Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
