# coding: utf-8

"""
    ONECTA Cloud API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.gateway_devices_gateway_device_id_management_points_embedded_id_characteristics_name_patch409_response import GatewayDevicesGatewayDeviceIdManagementPointsEmbeddedIdCharacteristicsNamePatch409Response

class TestGatewayDevicesGatewayDeviceIdManagementPointsEmbeddedIdCharacteristicsNamePatch409Response(unittest.TestCase):
    """GatewayDevicesGatewayDeviceIdManagementPointsEmbeddedIdCharacteristicsNamePatch409Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GatewayDevicesGatewayDeviceIdManagementPointsEmbeddedIdCharacteristicsNamePatch409Response:
        """Test GatewayDevicesGatewayDeviceIdManagementPointsEmbeddedIdCharacteristicsNamePatch409Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GatewayDevicesGatewayDeviceIdManagementPointsEmbeddedIdCharacteristicsNamePatch409Response`
        """
        model = GatewayDevicesGatewayDeviceIdManagementPointsEmbeddedIdCharacteristicsNamePatch409Response()
        if include_optional:
            return GatewayDevicesGatewayDeviceIdManagementPointsEmbeddedIdCharacteristicsNamePatch409Response(
                code = 'MANAGEMENT_POINT_BLOCKED',
                message = ''
            )
        else:
            return GatewayDevicesGatewayDeviceIdManagementPointsEmbeddedIdCharacteristicsNamePatch409Response(
                code = 'MANAGEMENT_POINT_BLOCKED',
                message = '',
        )
        """

    def testGatewayDevicesGatewayDeviceIdManagementPointsEmbeddedIdCharacteristicsNamePatch409Response(self):
        """Test GatewayDevicesGatewayDeviceIdManagementPointsEmbeddedIdCharacteristicsNamePatch409Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
