# coding: utf-8

"""
    ONECTA Cloud API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.gateway_device_api import GatewayDeviceApi


class TestGatewayDeviceApi(unittest.TestCase):
    """GatewayDeviceApi unit test stubs"""

    def setUp(self) -> None:
        self.api = GatewayDeviceApi()

    def tearDown(self) -> None:
        pass

    def test_gateway_devices_gateway_device_id_get(self) -> None:
        """Test case for gateway_devices_gateway_device_id_get

        Get the gatewayDevice and all its management points
        """
        pass

    def test_gateway_devices_get(self) -> None:
        """Test case for gateway_devices_get

        Get an array of gatewayDevices related to the user
        """
        pass


if __name__ == '__main__':
    unittest.main()
