# coding: utf-8

"""
    ONECTA Cloud API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.holiday_mode_api import HolidayModeApi


class TestHolidayModeApi(unittest.TestCase):
    """HolidayModeApi unit test stubs"""

    def setUp(self) -> None:
        self.api = HolidayModeApi()

    def tearDown(self) -> None:
        pass

    def test_gateway_devices_gateway_device_id_management_points_embedded_id_holiday_mode_post(self) -> None:
        """Test case for gateway_devices_gateway_device_id_management_points_embedded_id_holiday_mode_post

        Add a holiday period
        """
        pass


if __name__ == '__main__':
    unittest.main()
